In [53]:
import pandas as pd
import numpy

In [52]:
df = pd.read_csv('C:/Users/Daniel/Documents/Arbeit/diplomarbeit/urls.csv')
df

,https://www.derstandard.at/story/1358305150591/borschtsch,2016-11-28T09:36:39+01:00,kein Autor,"Zutaten für 8 Personen als Hauptspeise: 500 g Suppenknochen500 g Rindfleisch (Wade, ausgelöstes Beinfleisch oder Hals – wir haben uns für letzteren entschieden)Lorbeerblätter500 g KartoffelnSalz, Öl2 mittelgroße Zwiebeln250 g Karotten500 g rote Rüben1/2 Dose Tomaten3-4 Knoblauchzehen1/2 Kopf WeißkrautPetersilie, Dill, SauerrahmZwei große Töpfe, einer davon mindestens fünf Liter, eine sehr große Pfanne oder Wok und ein paar Stunden Zeit. Zubereitung: In der Ukraine gilt: vor jedem Teller Suppe ein Stamperl Wodka! Und rohe, geschälte Knoblauchzehen dazu. Gutes Gelingen!"
0,https://www.derstandard.at/story/1358304405960...,2016-11-28T09:36:39+01:00,kein Autor,Zutaten für 2 Personen: Zutaten Burger:250 g R...
1,https://www.derstandard.at/story/1355460339604...,2016-11-25T15:04:50+01:00,kein Autor,Zutaten für 2 Portionen: 10 große Champignons1...
2,https://www.derstandard.at/story/1358303673624...,2013-12-31T09:39:00+01:00,Birgit Riegler,Silvester Googlelässt 2013 mit einem eigenen D...
3,https://www.derstandard.at/story/1358303971837...,2013-07-27T22:36:00+02:00,Stefan Binder,Das westafrikanische Mali galt lange als demo...
4,https://www.derstandard.at/story/1358305287337...,2013-02-27T18:09:00+01:00,kein Autor,28.2.2013 Cartoon:Oliver Schopf 27.2.2013 Cart...
...,...,...,...,...
633272,https://www.derstandard.at/story/3000000230517...,2024-08-01T03:00:00.000Z,Sebastian FellnerMichael Völker,Wenige Wochen vor der Nationalratswahl machen ...
633273,https://www.derstandard.at/story/3000000230519...,2024-08-01T03:00:00.000Z,Walter Müller,Graz – Es war ein spektakuläres Zeichen des Hi...
633274,https://www.derstandard.at/story/3000000230565...,2024-08-01T03:00:00.000Z,Martin SchauhuberFranziska Zoidl,Schwimmen ist eine der gesündesten Sportarten ...
633275,https://www.derstandard.at/story/3000000229858...,2024-08-01T03:00:00.000Z,Paul M. Horntrich,"""Home sweet home"" ist auch hierzulande das Cre..."
633276,https://www.derstandard.at/story/3000000230584...,2024-08-01T03:00:00.000Z,Stefan Weiss,"Als sie kam, war Feuer am Dach. Andrea Mayer, ..."

In [54]:
print(df.columns)

Index(['https://www.derstandard.at/story/1358305150591/borschtsch',
       '2016-11-28T09:36:39+01:00', 'kein Autor',
       'Zutaten für 8 Personen als Hauptspeise: 500 g Suppenknochen500 g Rindfleisch (Wade, ausgelöstes Beinfleisch oder Hals – wir haben uns für letzteren entschieden)Lorbeerblätter500 g KartoffelnSalz, Öl2 mittelgroße Zwiebeln250 g Karotten500 g rote Rüben1/2 Dose Tomaten3-4 Knoblauchzehen1/2 Kopf WeißkrautPetersilie, Dill, SauerrahmZwei große Töpfe, einer davon mindestens fünf Liter, eine sehr große Pfanne oder Wok und ein paar Stunden Zeit. Zubereitung: In der Ukraine gilt: vor jedem Teller Suppe ein Stamperl Wodka! Und rohe, geschälte Knoblauchzehen dazu. Gutes Gelingen!'],
      dtype='object')

In [55]:
df.columns = ["url", "lastmod", "author", "content"]

In [56]:
df

,url,lastmod,author,content
0,https://www.derstandard.at/story/1358304405960...,2016-11-28T09:36:39+01:00,kein Autor,Zutaten für 2 Personen: Zutaten Burger:250 g R...
1,https://www.derstandard.at/story/1355460339604...,2016-11-25T15:04:50+01:00,kein Autor,Zutaten für 2 Portionen: 10 große Champignons1...
2,https://www.derstandard.at/story/1358303673624...,2013-12-31T09:39:00+01:00,Birgit Riegler,Silvester Googlelässt 2013 mit einem eigenen D...
3,https://www.derstandard.at/story/1358303971837...,2013-07-27T22:36:00+02:00,Stefan Binder,Das westafrikanische Mali galt lange als demo...
4,https://www.derstandard.at/story/1358305287337...,2013-02-27T18:09:00+01:00,kein Autor,28.2.2013 Cartoon:Oliver Schopf 27.2.2013 Cart...
...,...,...,...,...
633272,https://www.derstandard.at/story/3000000230517...,2024-08-01T03:00:00.000Z,Sebastian FellnerMichael Völker,Wenige Wochen vor der Nationalratswahl machen ...
633273,https://www.derstandard.at/story/3000000230519...,2024-08-01T03:00:00.000Z,Walter Müller,Graz – Es war ein spektakuläres Zeichen des Hi...
633274,https://www.derstandard.at/story/3000000230565...,2024-08-01T03:00:00.000Z,Martin SchauhuberFranziska Zoidl,Schwimmen ist eine der gesündesten Sportarten ...
633275,https://www.derstandard.at/story/3000000229858...,2024-08-01T03:00:00.000Z,Paul M. Horntrich,"""Home sweet home"" ist auch hierzulande das Cre..."
633276,https://www.derstandard.at/story/3000000230584...,2024-08-01T03:00:00.000Z,Stefan Weiss,"Als sie kam, war Feuer am Dach. Andrea Mayer, ..."

In [57]:
df.to_csv('test.csv', index=False)

In [58]:
df['lastmod']

0         2016-11-28T09:36:39+01:00
1         2016-11-25T15:04:50+01:00
2         2013-12-31T09:39:00+01:00
3         2013-07-27T22:36:00+02:00
4         2013-02-27T18:09:00+01:00
                    ...
633272     2024-08-01T03:00:00.000Z
633273     2024-08-01T03:00:00.000Z
633274     2024-08-01T03:00:00.000Z
633275     2024-08-01T03:00:00.000Z
633276     2024-08-01T03:00:00.000Z
Name: lastmod, Length: 633277, dtype: object

In [59]:
import pandas as pd
from dateutil import parser

# Custom function to parse each date string
def parse_dates(date_str):
    try:
        # Use dateutil.parser to handle timezone and convert to UTC
        return parser.parse(date_str)
    except Exception:
        return pd.NaT

# Apply the function to the 'lastmod' column
df['lastmod'] = df['lastmod'].apply(parse_dates)

# Print the result to check if the conversion works
print(df['lastmod'])

0         2016-11-28 09:36:39+01:00
1         2016-11-25 15:04:50+01:00
2         2013-12-31 09:39:00+01:00
3         2013-07-27 22:36:00+02:00
4         2013-02-27 18:09:00+01:00
                    ...
633272    2024-08-01 03:00:00+00:00
633273    2024-08-01 03:00:00+00:00
633274    2024-08-01 03:00:00+00:00
633275    2024-08-01 03:00:00+00:00
633276    2024-08-01 03:00:00+00:00
Name: lastmod, Length: 633277, dtype: object

In [60]:
df['lastmod']

0         2016-11-28 09:36:39+01:00
1         2016-11-25 15:04:50+01:00
2         2013-12-31 09:39:00+01:00
3         2013-07-27 22:36:00+02:00
4         2013-02-27 18:09:00+01:00
                    ...
633272    2024-08-01 03:00:00+00:00
633273    2024-08-01 03:00:00+00:00
633274    2024-08-01 03:00:00+00:00
633275    2024-08-01 03:00:00+00:00
633276    2024-08-01 03:00:00+00:00
Name: lastmod, Length: 633277, dtype: object

In [61]:
df.to_csv('ks.csv', index=False)

In [62]:
num_nat_values = df['lastmod'].isna().sum()


print(f"Number of NaT values: {num_nat_values}")

Number of NaT values: 0